@startuml
Lobby -> GameManager : startGame

GameManager -> PlayerManager : getPlayerGroup

PlayerManager -> PlayerGroup : init

loop playerCount times
    PlayerGroup -> Player : init

    Player -> CharacterLogicManager: requestCharacterLogicRef
    return characterLogicRef

    Player --> PlayerGroup : characterLogicRef
end

PlayerGroup --> PlayerManager: playerGroupRef

PlayerManager --> GameManager: playerGroupRef

GameManager -> CardsDeck : spawnCardsDeck

loop configuredCards times
    CardsDeck -> Card : init

    Card -> CardLogicManager: requestCardLogicRef
    return cardLogicRef

    Card --> CardsDeck : cardRef
end

CardsDeck --> GameManager: CardsDeckRef

GameManager --> Lobby : gameStarted

@enduml