@startuml
Lobby -> Game : startGame

Game -> PlayerGroup : spawnPlayerGroup

PlayerGroup -> CardsDeck : spawnCardsDeck

loop configuredCards times
    CardsDeck -> Card : init

    Card -> CardLogicManager: requestCardLogicRef
    return cardLogicRef

    Card --> CardsDeck : cardRef
end

CardsDeck --> PlayerGroup: cardsDeckRef


loop playerCount times
    PlayerGroup -> Player : init

    Player -> CharacterLogicManager: requestCharacterLogicRef
    return characterLogicRef

    Player --> PlayerGroup : characterLogicRef
end

PlayerGroup --> Game: playerGroupRef

Game --> Lobby : gameStarted

@enduml